apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-config-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/gitops-repo.git
    targetRevision: main
    path: config

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

